"""Create activities and sessions.

Revision ID: 0001
Revises: None
"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the initial schema; UUIDs are generated by the application."""
    op.create_table(
        "activities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.CheckConstraint(
            "length(trim(name)) > 0",
            name="ck_activities_name_not_blank",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_activities_name"),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("activity_id", sa.Uuid(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("comment", sa.String(), nullable=True),
        sa.CheckConstraint(
            "ended_at IS NULL OR ended_at >= started_at",
            name="ck_sessions_time_order",
        ),
        sa.CheckConstraint(
            "duration_seconds IS NULL OR duration_seconds >= 0",
            name="ck_sessions_duration_nonnegative",
        ),
        sa.CheckConstraint(
            "(ended_at IS NULL AND duration_seconds IS NULL) OR "
            "(ended_at IS NOT NULL AND duration_seconds IS NOT NULL)",
            name="ck_sessions_completion_consistent",
        ),
        sa.ForeignKeyConstraint(["activity_id"], ["activities.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_sessions_activity_id", "sessions", ["activity_id"])


def downgrade() -> None:
    """Drop both tables, including all their data."""
    op.drop_index("ix_sessions_activity_id", table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("activities")
